package com.yang.dao;

import java.util.List;

import com.yang.model.LoadingArm;

public interface LoadingArmMapper {
	List<LoadingArm> findall();
    /**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table t_loadingarm
	 *
	 * @mbggenerated
	 */
    int deleteByPrimaryKey(Integer wharfid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_loadingarm
     *
     * @mbggenerated
     */
    int insert(LoadingArm record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_loadingarm
     *
     * @mbggenerated
     */
    int insertSelective(LoadingArm record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_loadingarm
     *
     * @mbggenerated
     */
    LoadingArm selectByPrimaryKey(Integer wharfid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_loadingarm
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(LoadingArm record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_loadingarm
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(LoadingArm record);
}