package com.yang.model;

public class LoadingArm {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_loadingarm.wharfid
     *
     * @mbggenerated
     */
    private Integer wharfid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_loadingarm.loadingArmid
     *
     * @mbggenerated
     */
    private Integer loadingarmid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_loadingarm.maxCurrentSpeed
     *
     * @mbggenerated
     */
    private Integer maxcurrentspeed;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_loadingarm.loadingcapacity
     *
     * @mbggenerated
     */
    private Integer loadingcapacity;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_loadingarm.remark
     *
     * @mbggenerated
     */
    private String remark;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_loadingarm.wharfid
     *
     * @return the value of t_loadingarm.wharfid
     *
     * @mbggenerated
     */
    public Integer getWharfid() {
        return wharfid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_loadingarm.wharfid
     *
     * @param wharfid the value for t_loadingarm.wharfid
     *
     * @mbggenerated
     */
    public void setWharfid(Integer wharfid) {
        this.wharfid = wharfid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_loadingarm.loadingArmid
     *
     * @return the value of t_loadingarm.loadingArmid
     *
     * @mbggenerated
     */
    public Integer getLoadingarmid() {
        return loadingarmid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_loadingarm.loadingArmid
     *
     * @param loadingarmid the value for t_loadingarm.loadingArmid
     *
     * @mbggenerated
     */
    public void setLoadingarmid(Integer loadingarmid) {
        this.loadingarmid = loadingarmid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_loadingarm.maxCurrentSpeed
     *
     * @return the value of t_loadingarm.maxCurrentSpeed
     *
     * @mbggenerated
     */
    public Integer getMaxcurrentspeed() {
        return maxcurrentspeed;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_loadingarm.maxCurrentSpeed
     *
     * @param maxcurrentspeed the value for t_loadingarm.maxCurrentSpeed
     *
     * @mbggenerated
     */
    public void setMaxcurrentspeed(Integer maxcurrentspeed) {
        this.maxcurrentspeed = maxcurrentspeed;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_loadingarm.loadingcapacity
     *
     * @return the value of t_loadingarm.loadingcapacity
     *
     * @mbggenerated
     */
    public Integer getLoadingcapacity() {
        return loadingcapacity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_loadingarm.loadingcapacity
     *
     * @param loadingcapacity the value for t_loadingarm.loadingcapacity
     *
     * @mbggenerated
     */
    public void setLoadingcapacity(Integer loadingcapacity) {
        this.loadingcapacity = loadingcapacity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_loadingarm.remark
     *
     * @return the value of t_loadingarm.remark
     *
     * @mbggenerated
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_loadingarm.remark
     *
     * @param remark the value for t_loadingarm.remark
     *
     * @mbggenerated
     */
    public void setRemark(String remark) {
        this.remark = remark;
    }
}