package com.yang.model;

public class Wharf {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_wharf.wharfid
     *
     * @mbggenerated
     */
    private Integer wharfid;

	@Override
	public String toString() {
		return "Wharf [wharfid=" + wharfid + ",maxcurrentspeed=" + maxcurrentspeed + ", maxtonnage=" + maxtonnage
				+ ", mintonnage=" + mintonnage + ", maxcaptain=" + maxcaptain + ", minccaptain=" + minccaptain
				+ ", maxdraft=" + maxdraft + ", mindraft=" + mindraft + ", runningstate=" + runningstate + ", remark="
				+ remark + "]";
	}

	public static String getname() {
		return "['wharfid','maxcurrentspeed','maxtonnage','mintonnage','maxcaptain','minccaptain','maxdraft','mindraft','runningstate','remark','操作']";
	}
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column t_wharf.maxCurrentSpeed
	 *
	 * @mbggenerated
	 */
    private Integer maxcurrentspeed;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_wharf.maxTonnage
     *
     * @mbggenerated
     */
    private Integer maxtonnage;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_wharf.minTonnage
     *
     * @mbggenerated
     */
    private Integer mintonnage;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_wharf.maxCaptain
     *
     * @mbggenerated
     */
    private Integer maxcaptain;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_wharf.mincCaptain
     *
     * @mbggenerated
     */
    private Integer minccaptain;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_wharf.maxDraft
     *
     * @mbggenerated
     */
    private Integer maxdraft;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_wharf.minDraft
     *
     * @mbggenerated
     */
    private Integer mindraft;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_wharf.runningState
     *
     * @mbggenerated
     */
    private String runningstate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_wharf.remark
     *
     * @mbggenerated
     */
    private String remark;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_wharf.wharfid
     *
     * @return the value of t_wharf.wharfid
     *
     * @mbggenerated
     */
    public Integer getWharfid() {
        return wharfid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_wharf.wharfid
     *
     * @param wharfid the value for t_wharf.wharfid
     *
     * @mbggenerated
     */
    public void setWharfid(Integer wharfid) {
        this.wharfid = wharfid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_wharf.maxCurrentSpeed
     *
     * @return the value of t_wharf.maxCurrentSpeed
     *
     * @mbggenerated
     */
    public Integer getMaxcurrentspeed() {
        return maxcurrentspeed;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_wharf.maxCurrentSpeed
     *
     * @param maxcurrentspeed the value for t_wharf.maxCurrentSpeed
     *
     * @mbggenerated
     */
    public void setMaxcurrentspeed(Integer maxcurrentspeed) {
        this.maxcurrentspeed = maxcurrentspeed;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_wharf.maxTonnage
     *
     * @return the value of t_wharf.maxTonnage
     *
     * @mbggenerated
     */
    public Integer getMaxtonnage() {
        return maxtonnage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_wharf.maxTonnage
     *
     * @param maxtonnage the value for t_wharf.maxTonnage
     *
     * @mbggenerated
     */
    public void setMaxtonnage(Integer maxtonnage) {
        this.maxtonnage = maxtonnage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_wharf.minTonnage
     *
     * @return the value of t_wharf.minTonnage
     *
     * @mbggenerated
     */
    public Integer getMintonnage() {
        return mintonnage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_wharf.minTonnage
     *
     * @param mintonnage the value for t_wharf.minTonnage
     *
     * @mbggenerated
     */
    public void setMintonnage(Integer mintonnage) {
        this.mintonnage = mintonnage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_wharf.maxCaptain
     *
     * @return the value of t_wharf.maxCaptain
     *
     * @mbggenerated
     */
    public Integer getMaxcaptain() {
        return maxcaptain;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_wharf.maxCaptain
     *
     * @param maxcaptain the value for t_wharf.maxCaptain
     *
     * @mbggenerated
     */
    public void setMaxcaptain(Integer maxcaptain) {
        this.maxcaptain = maxcaptain;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_wharf.mincCaptain
     *
     * @return the value of t_wharf.mincCaptain
     *
     * @mbggenerated
     */
    public Integer getMinccaptain() {
        return minccaptain;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_wharf.mincCaptain
     *
     * @param minccaptain the value for t_wharf.mincCaptain
     *
     * @mbggenerated
     */
    public void setMinccaptain(Integer minccaptain) {
        this.minccaptain = minccaptain;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_wharf.maxDraft
     *
     * @return the value of t_wharf.maxDraft
     *
     * @mbggenerated
     */
    public Integer getMaxdraft() {
        return maxdraft;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_wharf.maxDraft
     *
     * @param maxdraft the value for t_wharf.maxDraft
     *
     * @mbggenerated
     */
    public void setMaxdraft(Integer maxdraft) {
        this.maxdraft = maxdraft;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_wharf.minDraft
     *
     * @return the value of t_wharf.minDraft
     *
     * @mbggenerated
     */
    public Integer getMindraft() {
        return mindraft;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_wharf.minDraft
     *
     * @param mindraft the value for t_wharf.minDraft
     *
     * @mbggenerated
     */
    public void setMindraft(Integer mindraft) {
        this.mindraft = mindraft;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_wharf.runningState
     *
     * @return the value of t_wharf.runningState
     *
     * @mbggenerated
     */
    public String getRunningstate() {
        return runningstate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_wharf.runningState
     *
     * @param runningstate the value for t_wharf.runningState
     *
     * @mbggenerated
     */
    public void setRunningstate(String runningstate) {
        this.runningstate = runningstate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_wharf.remark
     *
     * @return the value of t_wharf.remark
     *
     * @mbggenerated
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_wharf.remark
     *
     * @param remark the value for t_wharf.remark
     *
     * @mbggenerated
     */
    public void setRemark(String remark) {
        this.remark = remark;
    }
}